<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDQR2ZlB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDQR2ZlB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDQR2ZlB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDQR2ZlB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDQR2ZlB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DQR2ZlB',
    'container.build_id' => 'b2603a37',
    'container.build_time' => 1609694517,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDQR2ZlB');
